# The Docker image that will be used to build your app
image:  continuumio/anaconda3 #python:3.10-slim-bullseye  continuumio/miniconda3:latest
variables:
  GIT_STRATEGY: clone  
# Functions that should be executed before the build script is run

cache:
  key: venv-cache
  paths:
    - ../../local-runner-env3
    - ../../local-runner-envTests/

test:
  stage: test
  before_script:
    - git --version
    - pwd
    - ls -all
    - cd ..
    - ls -all
    - cd ..
    - ls -all
    - cd ..
    - ls -all
    - cd ..
    - ls -all
    - |
      VENV_DIR="../../local-runner-envTests"
      if [ ! -d "$VENV_DIR" ]; then
        echo "Creating new virtual environment..."
        python3 -m venv "$VENV_DIR"
      fi
      echo "Activating virtual environment..."
      source "$VENV_DIR/bin/activate"
      ls -all $VENV_DIR
      ls -all $VENV_DIR/anaconda3
      ls -all

      #if [ ! -d "$VENV_DIR/anaconda3/bin" ]; then
      #  echo "Installing conda..."
      #  wget -O "$VENV_DIR/anaconda3_install.sh" https://repo.anaconda.com/archive/Anaconda3-2025.06-1-Linux-x86_64.sh
      #  chmod +x "$VENV_DIR/anaconda3_install.sh"
      #  "$VENV_DIR/anaconda3_install.sh" -b -p "$VENV_DIR/anaconda3"
      #  echo "Creating conda environment for FELiCS..."
      #  conda env create -f installation/felics_v3.0.0_env.yml -y
      #  export PATH="$VENV_DIR/anaconda3/bin:$PATH"
      #  source activate base
      #  conda info --envs
      #  conda activate felics
      #  cd installation
      #  pip install -e .
      #  cd ..
      #else
      #  echo "Activating conda environment..."
      #  export PATH="$VENV_DIR/anaconda3/bin:$PATH"
      #  source activate base
      #  conda info --envs
      #  conda activate felics
      #fi
  script:
    - cd tests
    - python3 -m pytest 
  only:
    - development
    #- main

pages:
  before_script:
    - git --version
    - ls -all
    - |
      VENV_DIR="../../local-runner-env3"
      if [ ! -d "$VENV_DIR" ]; then
        echo "Creating new virtual environment..."	
        python3 -m venv "$VENV_DIR"
      fi
      echo "Activating virtual environment..."	
      source "$VENV_DIR/bin/activate"
      
      if ! sphinx-build --version 2>/dev/null; then
        echo "installing sphinx and dependencies..."	
        pip install -U pip
        pip install -U sphinx myst-parser sphinx-book-theme
        pip install -U sphinx-autoapi==3.0.0
        pip install sphinxcontrib-mermaid
      fi

  script:
  - cd documentation
  - mkdir ../public
  - python3 --version
  - pip list
  #- make html
  - sphinx-build -b html . _build
  - ls
  - cp -r _build/ ../public/.
  - cd ..
  - ls
  - cp -r public/_build/* public/
  - rm -r public/_build

  artifacts:
    paths:
      - public
  only:
    #- development
    - main
