# The Docker image that will be used to build your app
image:  continuumio/anaconda3 #python:3.10-slim-bullseye  continuumio/miniconda3:latest
variables:
  GIT_STRATEGY: clone  
# Functions that should be executed before the build script is run

cache:
  key: venv-cache
  paths:
    - local-runner-env3/
    - local-runner-envTests/

test:
  stage: test
  before_script:
    - git --version
    - pwd
    - ls -all
    - |
      if [ ! -d "local-runner-envTests" ] || [ ! -f "local-runner-envTests/bin/activate" ]; then
        echo "Creating new virtual environment..."
        python3 -m venv local-runner-envTests
      fi
      echo "Activating virtual environment..."
      source local-runner-envTests/bin/activate
      
      #if ! local-runner-envTests/bin/python3 -c "import FELiCS" 2>/dev/null; then
      #  echo "Installing FELiCS environment and dependecies..."
      #  /opt/conda/bin/conda env create -f ~/felics2.0/INSTALLATION/felics_v2.41_env.yml -y
      #  conda activate felics2025_dolfin9_v2
      #  pip install -e .
      #fi
      #  pip install -U pytest
      #  pip install -U pip
      #  pip install -U pytest
      #  --- insert FELiCS packages & pytest
  script:
    - cd TESTS
    #- python3 -m pytest 
  only:
    - development
    #- main

pages:
  before_script:
    - git --version
    - ls -all
    - |
      if [ ! -d "local-runner-env3" ]; then
        echo "Creating new virtual environment..."	
        python3 -m venv local-runner-env3
      fi
      echo "Activating virtual environment..."	
      source local-runner-env3/bin/activate
      
      if ! local-runner-env3/bin/sphinx-build --version 2>/dev/null; then
        echo "installing sphinx and dependencies..."	
        local-runner-env3/bin/pip install -U pip
        local-runner-env3/bin/pip install -U sphinx myst-parser sphinx-book-theme
        local-runner-env3/bin/pip install -U sphinx-autoapi==3.0.0
        local-runner-env3/bin/pip install sphinxcontrib-mermaid
      fi

  script:
  - cd DOCUMENTATION
  - mkdir ../public
  - python3 --version
  - ../local-runner-env3/bin/pip list
  #- make html
  - ../local-runner-env3/bin/sphinx-build -b html . _build
  - ls
  - cp -r _build/ ../public/.
  - cd ..
  - ls
  - cp -r public/_build/* public/
  - rm -r public/_build

  artifacts:
    paths:
      - public
  only:
    - development
    #- main