# The Docker image that will be used to build your app
image: python:3.10-slim-bullseye
variables:
  GIT_STRATEGY: clone  
# Functions that should be executed before the build script is run

cache:
  key: venv-cache
  paths:
    - local-runner-env/

test:
  stage: test
  before_script:
    - source /home/knechtel/.bashrc
    - conda activate felics2024_dolfin9
    - python3 -m pip install pytest
  script:
    - cd TESTS
    - python3 -m pytest 
    - conda deactivate 
  only:
    - development
    #- main

pages:
  before_script:
    - git --version
    - ls -all
    - |
      if [ ! -d "local-runner-env" ] || [ ! -f "local-runner-env/bin/activate" ]; then
        echo "\nCreating new virtual environment...\n"	
        python3 -m venv local-runner-env
      fi
      echo "Activating virtual environment..."	
      source local-runner-env/bin/activate
      
      if ! python -c "import sphinx" 2>/dev/null; then
        echo "installing sphinx and dependencies..."	
        pip install -U pip
        pip install -U sphinx myst-parser sphinx-book-theme sphinx-autoapi
      fi

  script:
  - cd DOCUMENTATION
  - mkdir ../public
  - python3 --version
  - pip list
  #- make html
  - sphinx-build -b html . _build
  - ls
  - cp -r _build/ ../public/.
  - cd ..
  - ls
  - cp -r public/_build/* public/
  - rm -r public/_build

  artifacts:
    paths:
      - public
  only:
    - development
    #- main
