[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "FELiCS"
version = "2.0"
description = "Finite Element Linearized Combustion Solver"
authors = [
    { name = "Thomas Kaiser", email = "t.kaiser@tu-berlin.de"}
]
dependencies = []

[tool.setuptools]
packages = ["FELiCS"]
package-dir = {"" = "src"}
