from Equations.speciesConservative.speciesConservativeEqAdvection import addSpeciesConservativeEqAdvection
from Equations.speciesConservative.speciesConservativeEqTimeDerivative import addSpeciesConservativeEqTimeDerivative
from Equations.speciesConservative.speciesConservativeEqDiffusion import addSpeciesConservativeEqDiffusion
from Equations.speciesConservative.speciesConservativeEqSourceTerms import addSpeciesConservativeEqSourceTerms
from Equations.speciesConservative.speciesConservativeEqBCs import addSpeciesConservativeEqBCs
def addSpeciesConservativeEq(self,fluc,X,mean,species,param):
	addSpeciesConservativeEqAdvection(self,fluc,X,mean,species,param)
	addSpeciesConservativeEqTimeDerivative(self,fluc,X,mean,species)
	addSpeciesConservativeEqDiffusion(self,fluc,X,mean,species,param)
	addSpeciesConservativeEqSourceTerms(self,X,mean,species,param)
	addSpeciesConservativeEqBCs(self,fluc,X,mean,species,param)

