[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "FELiCS"
version = "3.0.0"
description = "Finite Element Linearized Combustion Solver"
dependencies = []

[tool.setuptools]
packages = ["FELiCS","scripts","tests"]
package-dir = {"" = "../src", "scripts" = "../scripts", "tests" = "../tests"}
